const commentReply =[
    {
        id:1,
        name:'DOSA',
        text:"next sem to be online",
        heirarchy:0,
        repliedTo:false,
        time:'2020-05-05T23:37:49.992636+05:30',
        likes:69,
        children:[{
            id:2,
            name:'a Y19',
            text:';-( mujhe wapas jana hai',
            heirarchy:10,
            repliedTo:1,
            time:'2020-05-05T23:37:49.992636+05:30',
            likes:13,
            children:[{
                id:3,
                name:'IITK',
                text:'Want to buy BournVita?',
                heirarchy:20,
                repliedTo:2,
                time:'2020-05-05T23:37:49.992636+05:30',
                likes:333333,
                children:[],
            },]
        },
        ],
    },
    {
        id:4,
        name:'qwerty',
        text:'Hello,sir. What\'s up',
        heirarchy:0,
        repliedTo:0,
        time:'2020-05-05T23:37:49.992636+05:30',
        likes:12,
        children:[
            {
                id:5,
                name:'uiop',
                text:'Chala jaa yaha se',
                heirarchy:10,
                repliedTo:4,
                time:'2020-05-05T23:37:49.992636+05:30',
                likes:23,
                children:[],
            },
            {
                id:6,
                name:'asdfgh',
                text:'doin\' fine. what about you' ,
                heirarchy:10,
                repliedTo:4,
                time:'2020-05-05T23:37:49.992636+05:30',
                likes:34,
                children:[
                    {
                        id:7,
                        name:'uiop',
                        text:'finally someone to talk. yeahhh...',
                        heirarchy:20,
                        repliedTo:6,
                        time:'2020-05-05T23:37:49.992636+05:30',
                        likes:10,
                        children:[
                            {
                                id:8,
                                name:'asdfgh',
                                text:'from which year are you',
                                heirarchy:30,
                                repliedTo:7,
                                time:'2020-05-05T23:37:49.992636+05:30',
                                likes:2,
                                children:[
                                    {
                                        id:9,
                                        name:'uiop',
                                        text:'I am a freshie at BSBE Dept. B)',
                                        heirarchy:40,
                                        repliedTo:8,
                                        time:'2020-05-05T23:37:49.992636+05:30',
                                        likes:45,
                                        children:[],
                                    },
                                ],
                            },
                        ],
                    },
                ],
            },
            {
                id:10,
                name:'zxcvb',
                text:'whats up mtlb',
                heirarchy:10,
                repliedTo:4,
                time:'2020-05-05T23:37:49.992636+05:30',
                likes:67,
                children:[
                    {
                        id:11,
                        name:'qwerty',
                        text:'kuch nhi aaivaiy hi',
                        heirarchy:20,
                        repliedTo:10,
                        time:'2020-05-05T23:37:49.992636+05:30',
                        likes:78,
                        children:[
                            {
                                id:12,
                                name:'zxcvb',
                                text:'abbe yaha kya bakwas kar raha jaa endsem ka padh',
                                heirarchy:30,
                                repliedTo:11,
                                time:'2020-05-05T23:37:49.992636+05:30',
                                likes:3,
                                children:[],
                            },
                            {
                                id:13,
                                name:'zero',
                                text:'padhai vadhai sab waste,hain????',
                                heirarchy:30,
                                repliedTo:11,
                                time:'2020-05-05T23:37:49.992636+05:30',
                                likes:43,
                                children:[],
                            },
                        ],
                    },
                ],
            },
        ],
    },
]
export default commentReply;